version: '3'
services:
  s3server:
    image: scality/s3server:latest
    container_name: s3server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - s3data:/usr/src/app/localData
      - s3data:/usr/src/app/localMetadata
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=verySecretKey1
      - ENDPOINT=dvvdcasc10.rouen.francetelecom.fr
      - LOG_LEVEL=trace
      - SSL="FALSE"
volumes:
  s3data:
