---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: s3server2-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
